/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Presentacion;

import DataTransferObject.AsociacionesDTO;
import DataBussinessObject.Propietarios;
import Presentacion.Mototaxis;
import javax.swing.JOptionPane;
/**
 *
 * @author Usuario
 */
public class Form_agregar_propetario extends javax.swing.JFrame {
    int IdAsociacion;
    Propietarios propietarios=new Propietarios();
    public Mototaxis formularioPrincipal;
    /**
     * Creates new form Form_agregar_propetario
     */
    public Form_agregar_propetario(Mototaxis formularioPrincipal) {
        this.formularioPrincipal = formularioPrincipal;
        AsociacionesDTO asociacionesDTO = interconexion.getAsociacionesDTO();
        IdAsociacion = asociacionesDTO.getIdAsociacion();
        System.out.println(IdAsociacion);
        initComponents();      
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        btn_agregar_propietario = new javax.swing.JButton();
        txt_placa = new javax.swing.JTextField();
        txt_DNI = new javax.swing.JTextField();
        jTextField9 = new javax.swing.JTextField();
        txt_apellido_materno = new javax.swing.JTextField();
        txt_apellido_paterno = new javax.swing.JTextField();
        txt_nombre = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txt_soat = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jTextField8 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Leelawadee UI", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("NOMBRE");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 70, 90, 40));

        jLabel4.setFont(new java.awt.Font("Leelawadee UI", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("APELLIDOS MATERNOS");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 230, 170, 40));

        jLabel5.setFont(new java.awt.Font("Leelawadee UI", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("APELLIDOS PATERNOS");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 160, 180, 30));

        jLabel6.setFont(new java.awt.Font("Leelawadee UI", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("PLACA");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 400, 130, 30));

        jLabel7.setFont(new java.awt.Font("Leelawadee UI", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("REGISTRAR PROPETARIO");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 20, -1, 50));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Presentacion/Imagenes02/icons8-jefe-64.png"))); // NOI18N
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 20, 60, 50));

        btn_agregar_propietario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Presentacion/Imagenes02/icons8-agregar-carpeta-48.png"))); // NOI18N
        btn_agregar_propietario.setText("AGREGAR PROPIETARIO");
        btn_agregar_propietario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_agregar_propietarioActionPerformed(evt);
            }
        });
        getContentPane().add(btn_agregar_propietario, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 520, 480, 50));

        txt_placa.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 0, 255), new java.awt.Color(0, 0, 255)));
        getContentPane().add(txt_placa, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 430, 210, 40));

        txt_DNI.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.blue, java.awt.Color.blue));
        getContentPane().add(txt_DNI, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 350, 210, 30));

        jTextField9.setForeground(new java.awt.Color(204, 204, 255));
        jTextField9.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField9.setText("Ingrese la fecha de Caducidad");
        jTextField9.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.blue, java.awt.Color.blue));
        getContentPane().add(jTextField9, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 270, 210, 40));

        txt_apellido_materno.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(51, 51, 255), new java.awt.Color(0, 0, 255)));
        getContentPane().add(txt_apellido_materno, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 270, 210, 40));

        txt_apellido_paterno.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(0, 0, 255), java.awt.Color.blue));
        getContentPane().add(txt_apellido_paterno, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 200, 210, 30));

        txt_nombre.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(51, 51, 255), new java.awt.Color(0, 102, 204)));
        getContentPane().add(txt_nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 110, 210, 40));

        jLabel9.setFont(new java.awt.Font("Leelawadee UI", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("DNI");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 320, 61, 32));

        jLabel11.setFont(new java.awt.Font("Leelawadee UI", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("SOAT");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 70, 72, 38));

        txt_soat.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(51, 0, 255), new java.awt.Color(0, 0, 255)));
        getContentPane().add(txt_soat, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 110, 210, 40));

        jLabel12.setFont(new java.awt.Font("Leelawadee UI", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("TARJETA DE CIRCULACION");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 150, 200, 40));

        jTextField8.setForeground(new java.awt.Color(204, 204, 255));
        jTextField8.setText("Ingrese la fecha de Emision");
        jTextField8.setBorder(javax.swing.BorderFactory.createEtchedBorder(java.awt.Color.blue, java.awt.Color.blue));
        jTextField8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField8ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField8, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 200, 210, 40));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Presentacion/Imagenes02/Azul Minimalista Original Luz Azul Material De Fondo De Ensueño Ensueño de Pantalla Imagen para Descarga Gratuita - Pngtree.jpeg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 570, 610));

        jLabel3.setFont(new java.awt.Font("Leelawadee UI", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("APELLIDOS MATERNOS ");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 150, 180, 30));

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void btn_agregar_propietarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_agregar_propietarioActionPerformed
        // TODO add your handling code here:
        String mensaje=propietarios.agregar(txt_nombre.getText(),txt_apellido_paterno.getText(),
            txt_apellido_materno.getText(),txt_DNI.getText(),txt_soat.getText(),txt_placa.getText(),IdAsociacion);
        JOptionPane.showMessageDialog(this, mensaje, "Resultado de la agregacion",1);
        formularioPrincipal.refrescarUI(IdAsociacion);
        
    }//GEN-LAST:event_btn_agregar_propietarioActionPerformed

    private void jTextField8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField8ActionPerformed

    /**
     * @param args the command line arguments
     */
 

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_agregar_propietario;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    private javax.swing.JTextField txt_DNI;
    private javax.swing.JTextField txt_apellido_materno;
    private javax.swing.JTextField txt_apellido_paterno;
    private javax.swing.JTextField txt_nombre;
    private javax.swing.JTextField txt_placa;
    private javax.swing.JTextField txt_soat;
    // End of variables declaration//GEN-END:variables
}
